### ISSUE TITLE
Tests requiring current_user (sessions)

### ISSUE THREAD

**Issue by scripttease** [scripttease/ELSWC#2]
In: users_test.rb 
The tests for user images, and the tests for user show routes, are failing because the route /user/:username is now protected, and only current_user, as defined by: (in app.rb)
 ```ruby 
helpers do
    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
  end
```

can view these pages

**Comment by lpil** [comment]
Write code in blocks like this to have syntax highlighting
```
This is normal text
```ruby
# this is ruby
```
```

**Comment by scripttease** [comment]
Thank you, gorgeous

**Comment by scripttease** [comment]
Solved - thanks to https://github.com/goodgravy :) using rack.session

**Comment by lpil** [comment]
Woop
